<a href="https://colab.research.google.com/github/PratikshaDPai/TempoCCN_with_coch/blob/master/Coch_classification_keras_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Import statements
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report 
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
root_path = 'gdrive/My Drive/acm_mirium_tempo.rar/' 

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
%cd '/content/drive/My Drive/'


/content/drive/My Drive


In [ ]:
! git clone https://github.com/PratikshaDPai/tempo-cnn

Cloning into 'tempo-cnn'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 234 (delta 16), reused 14 (delta 4), pack-reused 189
Receiving objects: 100% (234/234), 154.81 MiB | 16.05 MiB/s, done.
Resolving deltas: 100% (108/108), done.
Checking out files: 100% (53/53), done.


In [ ]:
%cd tempocnn

/content/drive/My Drive/tempo-cnn/tempocnn


In [ ]:
! python setup.py install

running install
running bdist_egg
running egg_info
creating tempocnn.egg-info
writing tempocnn.egg-info/PKG-INFO
writing dependency_links to tempocnn.egg-info/dependency_links.txt
writing requirements to tempocnn.egg-info/requires.txt
writing top-level names to tempocnn.egg-info/top_level.txt
writing manifest file 'tempocnn.egg-info/SOURCES.txt'
writing manifest file 'tempocnn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/tempocnn
copying tempocnn/__init__.py -> build/lib/tempocnn
copying tempocnn/classifier.py -> build/lib/tempocnn
copying tempocnn/feature.py -> build/lib/tempocnn
copying tempocnn/tester.py -> build/lib/tempocnn
creating build/lib/tempocnn/models
copying tempocnn/models/cnn.h5 -> build/lib/tempocnn/models
copying tempocnn/models/fcn.h5 -> build/lib/tempocnn/models
copying tempocnn/models/ismir2018.h5 -> build/lib/tempocnn/models
copying tempocnn/mo

In [ ]:
! pip install jsonschema==3.2.0


  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
  Found existing installation: jsonschema 3.0.2
    Uninstalling jsonschema-3.0.2:
      Successfully uninstalled jsonschema-3.0.2


In [ ]:
! python -c "import importlib.metadata, shutil, pathlib; file = pathlib.Path(importlib.metadata.__file__); str(file).endswith('__init__.py') and shutil.rmtree(file.parent) and print('removed', file.parent)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib.metadata'


In [ ]:
! pip install lyon

In [ ]:
! python tester.py

2020-08-14 01:01:46.804425: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/content/drive/My Drive/tempo-cnn/tempocnn/wav_dataset2
2020-08-14 01:01:48.459304: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-08-14 01:01:48.463090: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-08-14 01:01:48.463132: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (28f73dfc605b): /proc/driver/nvidia/version does not exist
2020-08-14 01:01:48.468525: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz
2020-08-14 01:01:48.468849: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7840a80 initialized for platform Host (this does not guarantee that XLA will be used

Here we attempt to retrain a classifier model using keras load_model and .h5 model files for a second pass:

In [ ]:
import os
import pkgutil
import sys
import tempfile

import numpy as np
from tensorflow.python.keras.models import load_model

In [137]:
data_array=[[]]
import glob
import os
path=('/content/drive/My Drive/tempo-cnn/tempocnn/cnn_input')


for file in glob.glob(path+"/*.npy"):
  #print(file)
  name=os.path.basename(file)
  data_array.append([os.path.splitext(name)[0],np.load(file)])
  
print(data_array[3])

['1071042.clip.wav', array([[[[2.47339288e-06],
         [2.33966154e-06],
         [2.35375790e-06],
         ...,
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00]],

        [[7.64326969e-06],
         [7.17237802e-06],
         [7.30179523e-06],
         ...,
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00]],

        [[1.37600175e-05],
         [1.26726670e-05],
         [1.28789375e-05],
         ...,
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00]],

        ...,

        [[4.80404440e-05],
         [4.47017989e-05],
         [4.75229001e-05],
         ...,
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00]],

        [[4.77886553e-05],
         [4.47070009e-05],
         [4.73706315e-05],
         ...,
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00]],

        [[4.69604348e-05],
         [4.42697575e-05],
         [4.67758616e

In [106]:
df=[]
for i in range(1,len(data_array)-1):
  df.append(data_array[i][1])

In [109]:
print(df[1].shape)

(1, 40, 256, 1)


In [79]:
file =  os.getcwd()+'/models/fcn.h5' #_extract_from_package(resource)
print(file)
try:
    el = load_model(file)
except Exception as e:
    print('Failed to find a model named \'{}\'. Please check the model name.'.format(model_name),
          file=sys.stderr)
    raise e       


/content/drive/My Drive/tempo-cnn/tempocnn/models/fcn.h5


In [129]:
def estimate(data):
        """
        Estimate a tempo distribution.
        Probabilities are indexed, starting with 30 BPM and ending with 286 BPM.

        :param data: features
        :return: tempo probability distribution
        """
        assert len(data.shape) == 4, 'Input data must be four dimensional. Actual shape was ' + str(data.shape)
        assert data.shape[1] == 40, 'Second dim of data must be 40. Actual shape was ' + str(data.shape)
        assert data.shape[2] == 256, 'Third dim of data must be 256. Actual shape was ' + str(data.shape)
        assert data.shape[3] == 1, 'Fourth dim of data must be 1. Actual shape was ' + str(data.shape)
        return el.predict(data, data.shape[0])

estimate(df[1])

array([[2.87771400e-05, 1.93309879e-05, 9.22241670e-05, 5.49620891e-05,
        5.61434827e-05, 2.33558923e-04, 4.95513596e-05, 1.33336624e-04,
        3.41608597e-04, 7.18055235e-04, 2.48688069e-04, 1.65748585e-04,
        1.74565575e-04, 1.60244964e-02, 1.30895094e-03, 2.92405894e-04,
        1.27412775e-03, 1.02990505e-03, 2.83035431e-02, 4.22255322e-03,
        1.22165354e-02, 1.15150679e-03, 1.59799568e-02, 9.68269911e-03,
        9.03903798e-04, 3.30381421e-03, 8.65135691e-04, 4.49969526e-03,
        1.81412548e-02, 1.56245078e-03, 6.86009694e-03, 6.22720271e-03,
        3.79852485e-03, 3.10768164e-03, 1.30976946e-03, 7.78684160e-04,
        3.12684104e-02, 3.27560911e-03, 1.28164457e-03, 4.36521554e-03,
        8.28566123e-03, 5.90543542e-03, 1.83009461e-03, 2.50176433e-03,
        2.88614165e-03, 1.52608054e-02, 6.98944228e-03, 1.31455914e-03,
        3.12117417e-03, 1.91316928e-03, 8.34245328e-03, 7.09687301e-04,
        1.59992813e-03, 1.26096793e-03, 3.37348582e-04, 4.508260

In [135]:
train=[[]]
X=[]
target=[]
data = pd.read_csv(os.getcwd()+'/tempos.csv',header=None, names=(['file','tempo']), delimiter=',')
for j in range(1,len(data_array)-1):
  x=data_array[j]
  for i in range(0,len(data['file'])):
    if data['file'][i]==x[0]:
      train.append([x[1],data['tempo'][i],x[0]])
      target.append(data['tempo'][i])
      X.append(x[1])

In [139]:
## Split data into training and test 
Xi = X
y = target


X_train, X_test, y_train, y_test = train_test_split(Xi, y, test_size=0.2 ,random_state=0)
print(X_test[3].shape)

(1, 40, 256, 1)


In [146]:
## Scale data
def std_normalizer(data):
    """
    Normalizes data to zero mean and unit variance.
    Used by Mazurka models.

    :param data: data
    :return: standardized data
    """
    # normalize as 64 bit, to avoid numpy warnings
    data = data.astype(np.float64)
    mean = np.mean(data)
    std = np.std(data)
    if std != 0.:
        data = (data-mean) / std
    return data.astype(np.float16)

s=std_normalizer(Xi[1])    
print(s)

[[[[-0.4497 ]
   [-0.4878 ]
   [-0.507  ]
   ...
   [-0.588  ]
   [-0.588  ]
   [-0.588  ]]

  [[-0.11835]
   [-0.2393 ]
   [-0.2842 ]
   ...
   [-0.588  ]
   [-0.588  ]
   [-0.588  ]]

  [[ 0.2673 ]
   [ 0.04565]
   [-0.01613]
   ...
   [-0.588  ]
   [-0.588  ]
   [-0.588  ]]

  ...

  [[ 1.75   ]
   [ 1.27   ]
   [ 1.208  ]
   ...
   [-0.588  ]
   [-0.588  ]
   [-0.588  ]]

  [[ 1.731  ]
   [ 1.232  ]
   [ 1.162  ]
   ...
   [-0.588  ]
   [-0.588  ]
   [-0.588  ]]

  [[ 1.676  ]
   [ 1.193  ]
   [ 1.126  ]
   ...
   [-0.588  ]
   [-0.588  ]
   [-0.588  ]]]]


In [140]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [141]:
import csv
print(len(X_train))
result=zip(*X_train)
with open("out.csv", 'w') as myfile:
    wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
    for word in result:
        wr.writerow(word) 
xtr=pd.read_csv('out.csv',header=None)        

797


In [142]:

for i in range(len(xtr)):
  xtr[i]=np.array(xtr[i])
print(xtr[1])

0    [[[1.64781260e-06]\n  [1.38831427e-06]\n  [1.3...
Name: 1, dtype: object


In [143]:
regressor = LogisticRegression()  
regressor.fit(xtr, y_train)

ValueError: ignored

In [ ]:
import tensorflow as tf
from tensorflow import keras

## Setup
model = keras.Sequential([
    keras.Input(shape=4),
    keras.layers.Dense(15),
    keras.layers.Dense(15),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])



In [ ]:
print(confusion_matrix(y_test, y_hat))

[[14  3]
 [ 5 20]]


In [ ]:
print(classification_report(y_test, y_hat))

## accuracy is 74%
## precision, for 'M', is the precent of retunred 'M' that are really M: Precision = TP / [TP + FP]
## recall is the precent of true true 'M' that are returned: Recall = TP / [TP + FN]
## f1 score is related to accuracy

              precision    recall  f1-score   support

           0       0.74      0.82      0.78        17
           1       0.87      0.80      0.83        25

    accuracy                           0.81        42
   macro avg       0.80      0.81      0.81        42
weighted avg       0.82      0.81      0.81        42

